### ISSUE TITLE
Question about custom serializers

### ISSUE THREAD

**Issue by tanj** [mrevutskyi/flask-restless-ng#30]
I noticed the docs talk about [Custom Serialization](https://flask-restless-ng.readthedocs.io/en/latest/customizing.html#custom-serialization) but the examples were remove in 6c739545ef2221a8c5bd0fae71e67ead14eda063

Are the examples that are in the docs still the recommended way to do this or is there a new way or planned way for serialization to be done?

**Comment by mrevutskyi** [comment]
I've updated [Custom Serialization](https://flask-restless-ng.readthedocs.io/en/latest/customizing.html#custom-serialization) 

Instead of functions, it now uses objects (should implement `Serializer` class)

If you provide me more info on what you are trying to achieve with a custom serializer, I'll try to provide a better example

**Comment by tanj** [comment]
I took a read through the code and did see that you were using a Serializer class now, so I was able to do what I needed to by sub-classing as that was what you were doing. It was mainly that the docs didn't match the code, so I wanted to be sure I was taking the right approach. 

Thanks for updating the docs :)
